# Generated by Django 5.0.6 on 2024-10-23 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
            ],
            options={
                'db_table': 'plugin_emails_attachments',
            },
        ),
        migrations.CreateModel(
            name='CDRFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdr_file', models.FileField(blank=True, null=True, upload_to='cdr_files/')),
            ],
            options={
                'db_table': 'plugin_emails_cdr_files',
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('counter', models.IntegerField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Safe'), (2, 'Unsafe')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dispute',
            },
        ),
        migrations.CreateModel(
            name='DisputeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('counter', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dispute_info',
            },
        ),
        migrations.CreateModel(
            name='EmailDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(blank=True, max_length=90, null=True)),
                ('recievers_email', models.EmailField(max_length=200)),
                ('senders_email', models.CharField(blank=True, max_length=100, null=True)),
                ('eml_file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('plugin_id', models.CharField(blank=True, max_length=80, null=True)),
                ('msg_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('safe', 'Safe'), ('unsafe', 'Unsafe'), ('pending', 'Pending')], default='unsafe', max_length=50)),
                ('subject', models.TextField(blank=True, null=True)),
                ('urls', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('bcc', models.CharField(blank=True, max_length=100, null=True)),
                ('cc', models.CharField(blank=True, max_length=100, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
                ('ipv4', models.GenericIPAddressField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=255, null=True)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('cdr_file', models.FileField(blank=True, null=True, upload_to='cdr_files/')),
            ],
            options={
                'db_table': 'plugin_email_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PluginEnableDisable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plugin_enable_disable',
            },
        ),
        migrations.CreateModel(
            name='PluginInstallUninstall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('browser', models.CharField(max_length=30, null=True)),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uninstalled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plugin_install_uninstall',
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'plugin_emails_urls',
            },
        ),
    ]
