# Generated by Django 5.0.6 on 2024-10-22 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plugin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispute_infos_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputeinfo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dispute_infos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputeinfo',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='plugin.dispute'),
        ),
        migrations.AddField(
            model_name='disputeinfo',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cdrfile',
            name='email_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Emails_cdr_files', to='plugin.emaildetails'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='email_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Emailsattachments', to='plugin.emaildetails'),
        ),
        migrations.AddField(
            model_name='pluginenabledisable',
            name='plugin_install_uninstall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enable_disable_actions', to='plugin.plugininstalluninstall'),
        ),
        migrations.AddField(
            model_name='url',
            name='email_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Emaidetialsurls', to='plugin.emaildetails'),
        ),
    ]
