# Generated by Django 5.0.6 on 2024-10-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0004_alter_emaildetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildetails',
            name='status',
            field=models.CharField(choices=[('safe', 'Safe'), ('unsafe', 'Unsafe'), ('pending', 'Pending')], default='safe', max_length=50),
        ),
    ]
