# Generated by Django 5.0.6 on 2024-10-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
