# Generated by Django 5.0.6 on 2024-10-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_license_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='is_reserved',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
