name: My First GitHub Actions
on: [push] 

# on:
#   workflow_dispatch: {}
#   push:
#     branches:
#       - 'main'
#       - 'update_yml1'
env:
  sshKey: ${{ secrets.EC2_SSH_KEY }}
  ec2IP: ${{ secrets.EC2_PUBLIC_IP }}
  pat: ${{ secrets.GH_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ env.sshKey }}
      
      # - name: Clone Repository on EC2 using PAT
      #   run: |
      #     ssh -o StrictHostKeyChecking=no ubuntu@${{ env.ec2IP }} << 'EOF'
      #       # Clone the private repo on EC2 instance using PAT
      #       git clone https://${{ env.pat }}@github.com/EkVayu/IAF-Phishing.git /home/ubuntu/python-code/
      #     EOF
      - name: clear old python-code 
        run: | 
          sudo rm -rf /home/ubuntu/python-code/

      - name: Clone Repository on EC2 using PAT
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.ec2IP }} << 'EOF'
            # Clone the private repo on EC2 instance using PAT
            git clone https://${{ env.pat }}@github.com/EkVayu/IAF-Phishing.git /home/ubuntu/python-code/
            cd /home/ubuntu/python-code/
            # git checkout main
            sudo cp -r * /home/ubuntu/Updated_code_backend_deployment/
          EOF
